'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Main

    '''<summary>
    '''frmMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''grpNewPCPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpNewPCPos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''frmNewPcPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmNewPcPos As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''grpNewOpr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpNewOpr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''frmNewOpr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmNewOpr As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''grpOthOpr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpOthOpr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lstPcPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstPcPos As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''grpOprList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpOprList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lstOprList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstOprList As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''AdpPcPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdpPcPos As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AdpOprList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdpOprList As Global.System.Web.UI.WebControls.SqlDataSource
End Class
